=== Arelle/EdgarRenderer/validate/EFM/resources/edgartaxonomies/erxl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
<xsd:element name="Erxl">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Loc" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="version" use="required"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:pattern value="[1-9][0-9]*([\.][1-9][0-9]*)*"/></xsd:restriction></xsd:simpleType></xsd:attribute>
</xsd:complexType>
</xsd:element>
<xsd:element name="Loc">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Family" minOccurs="0">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Version" minOccurs="0">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Href" minOccurs="0">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LocalHref" minOccurs="0">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="AttType" minOccurs="0">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="FileTypeName" minOccurs="0">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Elements" minOccurs="1"/>
<xsd:element name="Namespace" minOccurs="0">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Prefix" minOccurs="0">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Arelle/EdgarRenderer/validate/EFM/resources/edgartaxonomies/ifrstaxonomies-all-years.xml
<?xml version="1.0" encoding="UTF-8"?>
<Erxl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns:xi="http://www.w3.org/2001/XInclude"
      xsi:noNamespaceSchemaLocation="../../../config/erxl.xsd" 
      version="34">
  <Loc><Family>IFRS</Family><Version>2013</Version><Href>http://xbrl.ifrs.org/taxonomy/2013-09-09/ifrs-cor_2013-09-09.xsd</Href><AttType>SCH</AttType><FileTypeName>Schema</FileTypeName><Elements>1</Elements><Namespace>http://xbrl.ifrs.org/taxonomy/2013-09-09/ifrs</Namespace><Prefix>currency</Prefix></Loc>
  <Loc><Family>IFRS</Family><Version>2014</Version><Href>http://xbrl.ifrs.org/taxonomy/2014-03-05/full_ifrs/full_ifrs-cor_2014-03-05.xsd</Href><AttType>SCH</AttType><FileTypeName>Schema</FileTypeName><Elements>1</Elements><Namespace>http://xbrl.ifrs.org/taxonomy/2014-03-05/ifrs-full</Namespace><Prefix>currency</Prefix></Loc>
  <Loc><Family>IFRS</Family><Version>2014</Version><Href>http://xbrl.ifrs.org/taxonomy/2014-03-05/ifrs_for_smes/ifrs_for_smes-cor_2014-03-05.xsd</Href><AttType>SCH</AttType><FileTypeName>Schema</FileTypeName><Elements>1</Elements><Namespace>http://xbrl.ifrs.org/taxonomy/2014-03-05/ifrs-smes</Namespace><Prefix>currency</Prefix></Loc>
  <Loc><Family>IFRS</Family><Version>2015</Version><Href>http://xbrl.ifrs.org/taxonomy/2015-03-11/full_ifrs/full_ifrs-cor_2015-03-11.xsd</Href><AttType>SCH</AttType><FileTypeName>Schema</FileTypeName><Elements>1</Elements><Namespace>http://xbrl.ifrs.org/taxonomy/2015-03-11/ifrs-full</Namespace><Prefix>ifrs</Prefix></Loc>
  <Loc><Family>IFRS</Family><Version>2016</Version><Href>http://xbrl.ifrs.org/taxonomy/2016-03-31/full_ifrs/full_ifrs-cor_2016-03-31.xsd</Href><AttType>SCH</AttType><FileTypeName>Schema</FileTypeName><Elements>1</Elements><Namespace>http://xbrl.ifrs.org/taxonomy/2016-03-31/ifrs-full</Namespace><Prefix>ifrs</Prefix></Loc>
  <Loc><Family>IFRS</Family><Version>2016.2</Version><Href>http://xbrl.ifrs.org/taxonomy/2016-09-12/full_ifrs/full_ifrs-cor_2016-09-12.xsd</Href><AttType>SCH</AttType><FileTypeName>Schema</FileTypeName><Elements>1</Elements><Namespace>http://xbrl.ifrs.org/taxonomy/2016-09-12/ifrs-full</Namespace><Prefix>ifrs</Prefix></Loc>
	<Loc>
		<Family>IFRS</Family>
		<Version>2021</Version>
		<Href>https://xbrl.sec.gov/dei/2021/dei-2021.xsd</Href>
		<AttType>SCH</AttType>
		<FileTypeName>Schema</FileTypeName>
		<Elements>1</Elements>
		<Namespace>http://xbrl.sec.gov/dei/2021</Namespace>
		<Prefix>dei</Prefix>
	</Loc>
</Erxl>

=== Arelle/EdgarRenderer/validate/EFM/resources/edgartaxonomies/extendedtaxonomies-all-years.xml
<?xml version="1.0" encoding="UTF-8"?>
<Erxl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns:xi="http://www.w3.org/2001/XInclude"
      xsi:noNamespaceSchemaLocation="../../../config/erxl.xsd" 
      version="34">
  <!-- SEC EDGAR taxonomies -->
  <xi:include href="edgartaxonomies-all-years.xml" xpointer="xpointer(/*/*)" />
  
  <!-- IFRS taxonomies added by Arelle 
       required standard taxonomy for US preparers doing 20F/40F conformant to EFM
       not for submission to EDGAR -->
  <xi:include href="ifrstaxonomies-all-years.xml" xpointer="xpointer(/*/*)" />

  <!-- Arelle taxonomy for cover documents
       required standard taxonomy by database loader
       (generated by Arelle, not for submission to EDGAR) -->
  <Loc><Family>Arelle</Family><Version>2014</Version><Href>http://arelle.org/2014/doc-2014-01-31.xsd</Href><AttType>SCH</AttType><FileTypeName>Schema</FileTypeName><Elements>1</Elements><Namespace>http://arelle.org/doc/2014-01-31</Namespace><Prefix>doc</Prefix></Loc>
</Erxl>
